name: Main

on: [push]

jobs:
  test-tempate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install -U cookiecutter

    - name: Try to use template
      run: |
        cd ..
        cookiecutter --no-input ./cookiecutter-python-template
        cd awesomium
        ls -la
        docker build -t test-image .
